### ISSUE TITLE
Bookmarks background...

### ISSUE THREAD

**Issue by vanja-san** [Catgrills/Melbourne#3]
`Style is just amazing! You are a super web designer! 👍 I love anime too! 😳`

On background you can see "standard background", is it possible to remove it?

![2019-04-04-03-44-26](https://user-images.githubusercontent.com/7201687/55512125-82b7bb00-568c-11e9-931f-2b9255351b73.png)

**Comment by vanja-san** [comment]
Are you no longer working with this style?

**Comment by Catgrills** [comment]
Hey vanja-san, I was a bit busy this day that's why I didn't answer right away. Are you talking about the white background ?

**Comment by vanja-san** [comment]
> 
> 
> Hey vanja-san, I was a bit busy these days that's why I didn't answer right away. Are you talking about the white background ?

The one that is inside your background. Maybe you should remove **shadow** and **border**.

_**On dark it looks like this:**_

![2019-04-07-21-47-56](https://user-images.githubusercontent.com/7201687/55685315-e1c44b00-597e-11e9-9ddd-ef1894280a37.png)

**Comment by Catgrills** [comment]
Oh, I see. Add the following code to the userChrome file :

#BMB_bookmarksPopup * {
	background: var(--nav-bg) !important;
	border: none !important;
	box-shadow: none !important;
}

**Comment by vanja-san** [comment]
> 
> 
> Oh, I see. Add the following code to the userChrome file :
> 
> #BMB_bookmarksPopup * {
> background: var(--nav-bg) !important;
> border: none !important;
> box-shadow: none !important;
> }

Thx! Very very nice style! 😊👍
